apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final  # Replace with your namespace if different
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: my_app:latest # Replace with your Docker image URL
        ports:
        - containerPort: 8080
        env:
        - name: MY_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MY_NAME
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: S3_BUCKET
        - name: S3_IMAGE_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: S3_IMAGE_KEY
