apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: my_app:latest  # Replace with your actual Docker image URL
        imagePullPolicy: Never  # Local pull
        ports:
        - containerPort: 8080  # Flask app runs on port 81
        env:
        - name: MY_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MY_NAME
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: S3_BUCKET
        - name: S3_IMAGE_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: S3_IMAGE_KEY
        - name: DB_HOST
          value: "mysql"  # Name of your MySQL service
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "employees"
