apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: my_db:latest  # Replace with your actual MySQL Docker image
        #imagePullPolicy: Always  #when ECR pull
        imagePullPolicy: Never  # Local pull

        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"  # Replace with a more secure password in production
