apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: final
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306        # Port for MySQL
      targetPort: 3306  # MySQL container port
  clusterIP: None      # Headless service (useful for accessing MySQL pod directly)
